// Code generated by mockery. DO NOT EDIT.

package simulator

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: amount
func (_m *MockService) Process(amount int) error {
	ret := _m.Called(amount)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockService_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - amount int
func (_e *MockService_Expecter) Process(amount interface{}) *MockService_Process_Call {
	return &MockService_Process_Call{Call: _e.mock.On("Process", amount)}
}

func (_c *MockService_Process_Call) Run(run func(amount int)) *MockService_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockService_Process_Call) Return(_a0 error) *MockService_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Process_Call) RunAndReturn(run func(int) error) *MockService_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
